[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/test-frameworks.html"
  to = "/test-frameworks"
  status = 301
  force = true

[[redirects]]
  from = "/comparison.html"
  to = "/test-frameworks"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
